FORMAT: 1A
HOST: localhost:4000

# Soccer API

This is a soccer API Example

# Group Players

## Players Collection [/players]

### Get all Players [GET /players]
+ Response 200 (application/json)
    + Attrbiutes
        - players (array)
            - id: `1` (number) - The id of the player
            - name: `Juanito Perez` (string) - The name of the player
            - nationality: `Colombia` (string) - The nationatily of the player
            - position: `Forward` (string) - The position of the player
            - birthdate: `1990-09-09` (date) - The birthdate of the player
            - created_at: `2016-08-04 15:41:13 -0400` (date) - The date of created this field
            - updated_at: `2016-09-04 11:30:00 -0400` (date) - The date of updated this field
